//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CineQuebec.Windows.Ressources.i18n {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CineQuebec.Windows.Ressources.i18n.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Abonnes.
        /// </summary>
        public static string admin_abonnes {
            get {
                return ResourceManager.GetString("admin.abonnes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Films.
        /// </summary>
        public static string admin_films {
            get {
                return ResourceManager.GetString("admin.films", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Utilisateurs.
        /// </summary>
        public static string admin_users {
            get {
                return ResourceManager.GetString("admin.users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajout.
        /// </summary>
        public static string ajout {
            get {
                return ResourceManager.GetString("ajout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le film a bien été ajouté.
        /// </summary>
        public static string ajoutReussi {
            get {
                return ResourceManager.GetString("ajoutReussi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La projection a bien été ajoutée.
        /// </summary>
        public static string ajoutReussiProjection {
            get {
                return ResourceManager.GetString("ajoutReussiProjection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à User a été ajouté avec succés..
        /// </summary>
        public static string ajoutUser {
            get {
                return ResourceManager.GetString("ajoutUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ciné Québec.
        /// </summary>
        public static string app_name {
            get {
                return ResourceManager.GetString("app_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connexion.
        /// </summary>
        public static string connexion_connect {
            get {
                return ResourceManager.GetString("connexion.connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Créer un compte.
        /// </summary>
        public static string connexion_creer {
            get {
                return ResourceManager.GetString("connexion.creer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mot de passe :.
        /// </summary>
        public static string connexion_password {
            get {
                return ResourceManager.GetString("connexion.password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Utilisateur :.
        /// </summary>
        public static string connexion_username {
            get {
                return ResourceManager.GetString("connexion.username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur.
        /// </summary>
        public static string erreur {
            get {
                return ResourceManager.GetString("erreur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une erreur s&apos;est produite.
        /// </summary>
        public static string erreurGenerique {
            get {
                return ResourceManager.GetString("erreurGenerique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une erreur s&apos;est produite lors de l&apos;ajout d&apos;un abonné.
        /// </summary>
        public static string errorAjoutUser {
            get {
                return ResourceManager.GetString("errorAjoutUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Username ou mot de passe est incorrect.
        /// </summary>
        public static string errorConnection {
            get {
                return ResourceManager.GetString("errorConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Un abonne existe déjà avec le meme username.
        /// </summary>
        public static string existingAbonne {
            get {
                return ResourceManager.GetString("existingAbonne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Doublon d&apos;un abonné.
        /// </summary>
        public static string existingAbonneTitre {
            get {
                return ResourceManager.GetString("existingAbonneTitre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modification.
        /// </summary>
        public static string modification {
            get {
                return ResourceManager.GetString("modification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le film a été bien modifié.
        /// </summary>
        public static string modificationReussi {
            get {
                return ResourceManager.GetString("modificationReussi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez selectionner un acteur pour ajouter.
        /// </summary>
        public static string selection_un_acteur_ajout {
            get {
                return ResourceManager.GetString("selection_un_acteur_ajout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez selectionner un acteur pour supprimer.
        /// </summary>
        public static string selection_un_acteur_supression {
            get {
                return ResourceManager.GetString("selection_un_acteur_supression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez selectionner une catégorie pour ajouter.
        /// </summary>
        public static string selection_un_cat_ajout {
            get {
                return ResourceManager.GetString("selection_un_cat_ajout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez selectionner une catégorie pour supprimer.
        /// </summary>
        public static string selection_un_categorie_supression {
            get {
                return ResourceManager.GetString("selection_un_categorie_supression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez selectionner un film pour ajouter.
        /// </summary>
        public static string selection_un_film_ajout {
            get {
                return ResourceManager.GetString("selection_un_film_ajout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez selectionner un film pour supprimer.
        /// </summary>
        public static string selection_un_film_supression {
            get {
                return ResourceManager.GetString("selection_un_film_supression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez selectionner un réalisateur pour ajouter.
        /// </summary>
        public static string selection_un_realisateur_ajout {
            get {
                return ResourceManager.GetString("selection_un_realisateur_ajout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez selectionner un réalisateur pour supprimer.
        /// </summary>
        public static string selection_un_realisateur_supression {
            get {
                return ResourceManager.GetString("selection_un_realisateur_supression", resourceCulture);
            }
        }
    }
}
